packages:
  - "."
  - "docs"
  - "website"
allowBuilds:
  esbuild: true
  sharp: true
  simple-git-hooks: true
  workerd: true
patchedDependencies:
  '@better-auth/oauth-provider@1.7.3': patches/@better-auth__oauth-provider@1.7.3.patch
