services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-mysecretpassword}
      - POSTGRES_DB=${DB_NAME:-mc_id}
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
