import { DocumentBuilder } from '@nestjs/swagger';

export const swaggerConfig = new DocumentBuilder()
  .setTitle('MC-ID API')
  .setDescription(
    'The backend API for https://mc-id.com/ that provides authentication for Minecraft accounts.',
  )
  .setVersion('1')
  .addTag('mc-id')
  .setContact('Tonantzintla', 'https://github.com/Tonantzintla', '')
  .addBearerAuth(
    {
      description:
        'Plugin key specified in the environment variable PLUGIN_KEY',
      scheme: 'Bearer',
      type: 'http',
    },
    'PluginKey',
  )
  .addBearerAuth(
    {
      description: 'JWT token generated by the better auth system',
      scheme: 'Bearer',
      bearerFormat: 'JWT',
      type: 'http',
    },
    'JWTBearerAuth',
  )
  .build();
