name: Release Plugin

on:
  push:
    branches:
      - main
    paths:
      - ".changeset/**"
      - "plugin/**"
      - "package.json"
      - "CHANGELOG.md"
      - ".github/workflows/**"
      - "pnpm-workspace.yaml"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node & PNPM
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: 25
          distribution: "temurin"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Install dependencies
        run: pnpm install

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Release PR or Publish
        uses: changesets/action@v2
        with:
          commit-message: "chore(release): version packages"
          pr-title: "chore(release): version packages"
          version-script: pnpm changeset version
          publish-script: pnpm run changeset:publish
          github-token: ${{ secrets.PAT_TOKEN }}
          create-github-releases: false
          push-git-tags: false
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
